const ROLES = {
  STUDENT: 'student',
  TNP: 'tnp',
  ADMIN: 'admin',
};

const CATEGORIES = {
  CAT1: 'CAT1',
  CAT2: 'CAT2',
  CAT3: 'CAT3',
};

const BANDS = {
  NORMAL: 'NORMAL',
  DREAM: 'DREAM',
  SUPER_DREAM: 'SUPER_DREAM',
};

const PLACEMENT_TYPES = {
  NORMAL: 'NORMAL',
  PLI: 'PLI',
  AEDP: 'AEDP',
};

const PLACEMENT_STATUS = {
  ACTIVE: 'ACTIVE',
  AEDP_SELECTED: 'AEDP_SELECTED',
};

const OFFER_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  WITHDRAWN: 'WITHDRAWN',
};

const DEFAULT_CATEGORY_BAND_MAP = {
  CAT1: [BANDS.NORMAL, BANDS.DREAM, BANDS.SUPER_DREAM],
  CAT2: [BANDS.NORMAL, BANDS.DREAM],
  CAT3: [BANDS.NORMAL],
};

const DEFAULT_BAND_THRESHOLDS = {
  normalMax: 5,
  dreamMax: 10,
};

module.exports = {
  ROLES,
  CATEGORIES,
  BANDS,
  PLACEMENT_TYPES,
  PLACEMENT_STATUS,
  OFFER_STATUS,
  DEFAULT_CATEGORY_BAND_MAP,
  DEFAULT_BAND_THRESHOLDS,
};
